openapi: 3.0.0
info:
  title: ResultModel API
  description: Définition du modèle ResultModel pour une application Android
  version: 1.0.0

paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML
      responses:
        "200":
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

components:
  schemas:
    ResultModel:
      type: object
      required:
        - shouldReadMrz
        - shouldShowReview
        - enabledValidation
        - listCountries
      properties:
        shouldReadMrz:
          type: boolean
          description: Indique si la lecture MRZ est activée
        shouldShowReview:
          type: boolean
          description: Indique si l'écran de révision doit être affiché
        enabledValidation:
          type: boolean
          description: Indique si la validation est activée
        listCountries:
          type: array
          description: Liste des codes de pays
          items:
            type: string
        additionalData:
          type: string
          nullable: true
          description: Données supplémentaires optionnelles